# Generated by Django 6.0.1 on 2026-01-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hierarchy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('date', models.DateField()),
                ('path', models.TextField()),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.directory')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.user'),
        ),
    ]
