# Generated by Django 6.0.1 on 2026-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='hierarchy',
            field=models.TextField(),
        ),
    ]
