# Generated by Django 6.0.1 on 2026-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_directory_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
