# Generated by Django 6.0.1 on 2026-02-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_directory_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
        migrations.AlterField(
            model_name='directory',
            name='level',
            field=models.IntegerField(),
        ),
    ]
